"""remove indexing from user_id

Revision ID: 1e14f4b42a69
Revises: c3445a1d8c06
Create Date: 2024-11-14 21:37:05.101596

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e14f4b42a69'
down_revision = 'c3445a1d8c06'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.drop_index('ix_articles_user_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.create_index('ix_articles_user_id', ['user_id'], unique=False)

    # ### end Alembic commands ###
