"""article type default

Revision ID: 53758b4429cd
Revises: e4c40c172519
Create Date: 2024-11-14 20:30:43.862637

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import ENUM


# revision identifiers, used by Alembic.
revision = '53758b4429cd'
down_revision = 'e4c40c172519'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.alter_column('article_type',
               existing_type=sa.VARCHAR(length=8),
               type_=ENUM('normal', 'breaking', 'top', name='article_type'),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.alter_column('article_type',
               existing_type=ENUM('normal', 'breaking', 'top', 
                                  name='article_type'),
               type_=sa.VARCHAR(length=8),
               existing_nullable=False)

    # ### end Alembic commands ###
