"""slug field added

Revision ID: 705deb2fb3de
Revises: 1e14f4b42a69
Create Date: 2024-11-15 00:57:54.066836

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '705deb2fb3de'
down_revision = '1e14f4b42a69'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('slug', sa.String(length=255), nullable=True))
        batch_op.create_index(batch_op.f('ix_articles_slug'), ['slug'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_articles_slug'))
        batch_op.drop_column('slug')

    # ### end Alembic commands ###
