"""make source nullable

Revision ID: c3445a1d8c06
Revises: 64698b6acbf2
Create Date: 2024-11-14 21:32:13.872334

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3445a1d8c06'
down_revision = '64698b6acbf2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.alter_column('source_id',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.alter_column('source_id',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###
