"""article type

Revision ID: e4c40c172519
Revises: f764d21e4987
Create Date: 2024-11-14 20:21:59.311957

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4c40c172519'
down_revision = 'f764d21e4987'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('article_type', sa.Enum('normal', 'breaking', 'top', native_enum=False), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.drop_column('article_type')

    # ### end Alembic commands ###
